# Puerto del servidor
server.port=8082

# Configuración de la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/puente_blanco?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# Driver JDBC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración para ejecutar data.sql automáticamente
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Zona horaria
spring.jackson.time-zone=America/Lima

# Configuración de logs de SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# JWT CONFIG
jwt.secret=${JWT_SECRET:6B6F4A772F2F3D4B635066546A576E5A7234753778214125442A472D4B615064}
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG
spring.jmx.enabled=false

# TOKENS STRIPE (Con valores por defecto para que funcione en tu PC)
stripe.secret.key=${STRIPE_SECRET_KEY:sk_test_51RalEZRoNCO7cM0RsG5jcqkDeE5PyZ77W5Hj4FOk5b0cIjzQQihhN2YT5bmtkkoH4y38Wcc9KVuIY6PyxDmFqIkj00JKQ5oMIM}
stripe.public.key=${STRIPE_PUBLIC_KEY:pk_test_51RalEZRoNCO7cM0RzhlBfpNSCY3xvpl9MVsWBHSe4KE98iAtBeZ91f8JCPyL7K7Ti5xsDLDL5XGM7bcz5401VQGo00iBzXiRoV}

# Configuración de Correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lacoquaangela@gmail.com
# Contraseña de aplicación como valor por defecto
spring.mail.password=${MAIL_PASSWORD:abeounidqhqqrpio}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Niveles de Log
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework=INFO
logging.level.com.puenteblanco=DEBUG

# Configuración de recursos estáticos
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false